-- ==============================================================================
-- InboxWa Full Supabase PostgreSQL Schema
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/wqbsglfllvsmylejpflq/sql/new
-- ==============================================================================

-- 1. LEADS TABLE (CRM & Public Forms)
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT DEFAULT 'contact',
    name TEXT NOT NULL,
    business TEXT,
    email TEXT,
    phone TEXT,
    whatsapp TEXT,
    country TEXT,
    city TEXT,
    product TEXT,
    requirement TEXT,
    message TEXT,
    preferred_date TEXT,
    preferred_time TEXT,
    source_page TEXT,
    referrer TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    ip TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SETTINGS TABLE (Platform & Theme Configuration)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SITE SECTIONS TABLE (Live Website CMS)
CREATE TABLE IF NOT EXISTS public.site_sections (
    section TEXT NOT NULL,
    field TEXT NOT NULL,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (section, field)
);

-- 4. POSTS TABLE (Blog & Articles)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    category TEXT DEFAULT 'General',
    excerpt TEXT,
    content TEXT,
    image TEXT,
    author TEXT DEFAULT 'InboxWa Team',
    status TEXT DEFAULT 'published',
    views INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. COMMENTS TABLE
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT DEFAULT 1,
    post_title TEXT DEFAULT 'Hello world!',
    author_name TEXT NOT NULL,
    author_email TEXT,
    author_url TEXT,
    author_ip TEXT DEFAULT '127.0.0.1',
    content TEXT NOT NULL,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PRICING PLANS TABLE
CREATE TABLE IF NOT EXISTS public.pricing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    badge TEXT,
    tagline TEXT,
    monthly INT DEFAULT 0,
    yearly INT DEFAULT 0,
    setup_fee_monthly INT DEFAULT 0,
    setup_fee_yearly INT DEFAULT 0,
    cta_text TEXT DEFAULT 'Start Free',
    cta_link TEXT DEFAULT '/auth/register',
    channels_json TEXT,
    features_json TEXT,
    is_popular INT DEFAULT 0,
    sort_order INT DEFAULT 0
);

-- 7. TESTIMONIALS TABLE
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    company TEXT,
    avatar TEXT,
    rating INT DEFAULT 5,
    quote TEXT NOT NULL,
    sort_order INT DEFAULT 0
);

-- 8. FAQS TABLE
CREATE TABLE IF NOT EXISTS public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT DEFAULT 'general',
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    sort_order INT DEFAULT 0
);

-- 9. CUSTOM LOCATIONS TABLE (SEO landing pages)
CREATE TABLE IF NOT EXISTS public.custom_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    type TEXT DEFAULT 'city',
    primary_keyword TEXT,
    meta_title TEXT,
    meta_description TEXT,
    hero_title TEXT,
    hero_description TEXT,
    areas_json TEXT,
    content TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- ROW LEVEL SECURITY (ALLOW READ/WRITE WITH ANON/SERVICE KEY)
-- ==============================================================================
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read/Write Leads" ON public.leads;
CREATE POLICY "Public Read/Write Leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Settings" ON public.settings;
CREATE POLICY "Public Read/Write Settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Site Sections" ON public.site_sections;
CREATE POLICY "Public Read/Write Site Sections" ON public.site_sections FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Posts" ON public.posts;
CREATE POLICY "Public Read/Write Posts" ON public.posts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Comments" ON public.comments;
CREATE POLICY "Public Read/Write Comments" ON public.comments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Pricing Plans" ON public.pricing_plans;
CREATE POLICY "Public Read/Write Pricing Plans" ON public.pricing_plans FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Testimonials" ON public.testimonials;
CREATE POLICY "Public Read/Write Testimonials" ON public.testimonials FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write FAQs" ON public.faqs;
CREATE POLICY "Public Read/Write FAQs" ON public.faqs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read/Write Custom Locations" ON public.custom_locations;
CREATE POLICY "Public Read/Write Custom Locations" ON public.custom_locations FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- SEED INITIAL DEFAULT SETTINGS
-- ==============================================================================
INSERT INTO public.settings (key, value) VALUES
    ('admin_user', 'admin'),
    ('admin_pass', 'admin123'),
    ('site_title', 'InboxWa'),
    ('site_tagline', 'WhatsApp Marketing & Automation Platform'),
    ('support_whatsapp', '918050854445'),
    ('admin_email', 'mail@inboxwa.com'),
    ('sales_email', 'sales@inboxwa.com'),
    ('support_email', 'support@inboxwa.com'),
    ('theme_primary_color', '#8B5CF6'),
    ('theme_primary_hover', '#7C3AED'),
    ('theme_accent_color', '#06B6D4'),
    ('theme_success_color', '#16A34A'),
    ('theme_bg_color', '#FFFFFF'),
    ('theme_text_color', '#0F172A'),
    ('theme_palette_preset', 'modern-violet'),
    ('users_can_register', '0'),
    ('default_role', 'subscriber'),
    ('site_language', 'en_US'),
    ('timezone_string', 'UTC+0'),
    ('date_format', 'F j, Y'),
    ('time_format', 'g:i a'),
    ('start_of_week', '1')
ON CONFLICT (key) DO NOTHING;

-- SEED SAMPLE POST
INSERT INTO public.posts (title, slug, category, excerpt, content, author, status) VALUES
    ('Hello world!', 'hello-world', 'General', 'Welcome to InboxWa. This is your first post. Edit or delete it, then start publishing!', 'Welcome to InboxWa. This is your first post. Edit or delete it, then start writing!', 'InboxWa Team', 'published')
ON CONFLICT (slug) DO NOTHING;

-- SEED SAMPLE COMMENT
INSERT INTO public.comments (post_id, post_title, author_name, author_email, author_url, content, status) VALUES
    (1, 'Hello world!', 'An InboxWa User', 'support@inboxwa.com', 'https://inboxwa.com', 'Hi, this is a comment. To get started with moderating, editing, and deleting comments, please visit the Comments screen in the dashboard.', 'approved')
ON CONFLICT DO NOTHING;
